// <auto-generated />
using System;
using EfCoreOwnedType.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreOwnedType.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCoreOwnedType.Entities.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AddressId")
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataId")
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DataId");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "uorM-JDuHEaAR5RAfoOHeA",
                            AccountType = "IsAdmin",
                            AddressId = "TwFrjqcdEE2PvTh2SDNVDA",
                            Created = new DateTime(2022, 2, 23, 12, 38, 6, 165, DateTimeKind.Utc).AddTicks(3804),
                            DataId = "asF5V8C9706efOtbfaRn_Q",
                            IsDeleted = false,
                            LastActive = new DateTime(2022, 2, 23, 12, 38, 6, 165, DateTimeKind.Utc).AddTicks(3803),
                            Mail = "test@mail.de",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("EFCoreOwnedType.Entities.Contact.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TwFrjqcdEE2PvTh2SDNVDA",
                            City = "Citname",
                            HouseNumber = "1",
                            IsDeleted = false,
                            PostalCode = "12345",
                            Street = "Street"
                        });
                });

            modelBuilder.Entity("EFCoreOwnedType.Entities.Person.PersonalData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BirthName")
                        .HasColumnType("longtext");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyName")
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAffix")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResidentSince")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Salutation")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxNo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PersonalData");

                    b.HasData(
                        new
                        {
                            Id = "asF5V8C9706efOtbfaRn_Q",
                            BirthDate = new DateTime(2002, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "PersonBirth",
                            BirthPlace = "Cityname",
                            FamilyName = "Person",
                            FirstName = "Test",
                            Gender = "male",
                            IsDeleted = false,
                            Salutation = "Herr"
                        });
                });

            modelBuilder.Entity("EFCoreOwnedType.Entities.Account.User", b =>
                {
                    b.HasOne("EFCoreOwnedType.Entities.Contact.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("EFCoreOwnedType.Entities.Person.PersonalData", "Data")
                        .WithMany()
                        .HasForeignKey("DataId");

                    b.Navigation("Address");

                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
